# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'xrdui.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(979, 667)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionOpen_Multiple = QAction(MainWindow)
        self.actionOpen_Multiple.setObjectName(u"actionOpen_Multiple")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionPrint = QAction(MainWindow)
        self.actionPrint.setObjectName(u"actionPrint")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        self.actionReframe_Horizontally = QAction(MainWindow)
        self.actionReframe_Horizontally.setObjectName(u"actionReframe_Horizontally")
        self.actionReframe_Vertically = QAction(MainWindow)
        self.actionReframe_Vertically.setObjectName(u"actionReframe_Vertically")
        self.actionHorizontalLinear = QAction(MainWindow)
        self.actionHorizontalLinear.setObjectName(u"actionHorizontalLinear")
        self.actionHorizontalLogarithmic = QAction(MainWindow)
        self.actionHorizontalLogarithmic.setObjectName(u"actionHorizontalLogarithmic")
        self.actionMean = QAction(MainWindow)
        self.actionMean.setObjectName(u"actionMean")
        self.actionLinear_Regression = QAction(MainWindow)
        self.actionLinear_Regression.setObjectName(u"actionLinear_Regression")
        self.actionM2 = QAction(MainWindow)
        self.actionM2.setObjectName(u"actionM2")
        self.actionM4_q = QAction(MainWindow)
        self.actionM4_q.setObjectName(u"actionM4_q")
        self.actionFourier = QAction(MainWindow)
        self.actionFourier.setObjectName(u"actionFourier")
        self.actionAll = QAction(MainWindow)
        self.actionAll.setObjectName(u"actionAll")
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        self.actionDelete_Chart = QAction(MainWindow)
        self.actionDelete_Chart.setObjectName(u"actionDelete_Chart")
        self.actionVerticalLinear = QAction(MainWindow)
        self.actionVerticalLinear.setObjectName(u"actionVerticalLinear")
        self.actionVerticalLogarithmic = QAction(MainWindow)
        self.actionVerticalLogarithmic.setObjectName(u"actionVerticalLogarithmic")
        self.actionM1 = QAction(MainWindow)
        self.actionM1.setObjectName(u"actionM1")
        self.actionM3 = QAction(MainWindow)
        self.actionM3.setObjectName(u"actionM3")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.frameChart = QFrame(self.centralwidget)
        self.frameChart.setObjectName(u"frameChart")
        self.frameChart.setFrameShape(QFrame.StyledPanel)
        self.frameChart.setFrameShadow(QFrame.Raised)
        self.verticalLayout_6 = QVBoxLayout(self.frameChart)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.frame = QFrame(self.frameChart)
        self.frame.setObjectName(u"frame")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_7 = QVBoxLayout(self.frame)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)

        self.verticalLayout_6.addWidget(self.frame)

        self.frameScroll = QFrame(self.frameChart)
        self.frameScroll.setObjectName(u"frameScroll")
        self.frameScroll.setMinimumSize(QSize(0, 21))
        self.frameScroll.setFrameShape(QFrame.StyledPanel)
        self.frameScroll.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.frameScroll)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.scrollArea = QScrollArea(self.frameScroll)
        self.scrollArea.setObjectName(u"scrollArea")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Maximum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy1)
        self.scrollArea.setMaximumSize(QSize(16777215, 60))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 750, 58))
        self.horizontalLayout_2 = QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frameSheet = QFrame(self.scrollAreaWidgetContents_3)
        self.frameSheet.setObjectName(u"frameSheet")
        self.frameSheet.setFrameShape(QFrame.StyledPanel)
        self.frameSheet.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.frameSheet)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)

        self.horizontalLayout_2.addWidget(self.frameSheet, 0, Qt.AlignLeft|Qt.AlignTop)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)

        self.horizontalLayout_3.addWidget(self.scrollArea)

        self.pushButtonPlus = QPushButton(self.frameScroll)
        self.pushButtonPlus.setObjectName(u"pushButtonPlus")
        self.pushButtonPlus.setMaximumSize(QSize(40, 60))

        self.horizontalLayout_3.addWidget(self.pushButtonPlus, 0, Qt.AlignRight)


        self.verticalLayout_6.addWidget(self.frameScroll)


        self.horizontalLayout.addWidget(self.frameChart)

        self.frameSideBar = QFrame(self.centralwidget)
        self.frameSideBar.setObjectName(u"frameSideBar")
        self.frameSideBar.setMaximumSize(QSize(176, 16777215))
        self.frameSideBar.setFrameShape(QFrame.StyledPanel)
        self.frameSideBar.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.frameSideBar)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.groupBoxReframe = QGroupBox(self.frameSideBar)
        self.groupBoxReframe.setObjectName(u"groupBoxReframe")
        self.groupBoxReframe.setMinimumSize(QSize(152, 103))
        self.verticalLayout = QVBoxLayout(self.groupBoxReframe)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.pushButtonHorizontalReframe = QPushButton(self.groupBoxReframe)
        self.pushButtonHorizontalReframe.setObjectName(u"pushButtonHorizontalReframe")
        self.pushButtonHorizontalReframe.setMinimumSize(QSize(0, 40))

        self.verticalLayout.addWidget(self.pushButtonHorizontalReframe)

        self.pushButtonVerticalReframe = QPushButton(self.groupBoxReframe)
        self.pushButtonVerticalReframe.setObjectName(u"pushButtonVerticalReframe")
        self.pushButtonVerticalReframe.setMinimumSize(QSize(0, 40))

        self.verticalLayout.addWidget(self.pushButtonVerticalReframe)


        self.verticalLayout_3.addWidget(self.groupBoxReframe)

        self.groupBoxVal = QGroupBox(self.frameSideBar)
        self.groupBoxVal.setObjectName(u"groupBoxVal")
        self.groupBoxVal.setMinimumSize(QSize(152, 103))
        self.verticalLayout_2 = QVBoxLayout(self.groupBoxVal)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.pushButtonMean = QPushButton(self.groupBoxVal)
        self.pushButtonMean.setObjectName(u"pushButtonMean")
        self.pushButtonMean.setMinimumSize(QSize(0, 40))

        self.verticalLayout_2.addWidget(self.pushButtonMean)

        self.pushButtonRegLin = QPushButton(self.groupBoxVal)
        self.pushButtonRegLin.setObjectName(u"pushButtonRegLin")
        self.pushButtonRegLin.setMinimumSize(QSize(0, 40))

        self.verticalLayout_2.addWidget(self.pushButtonRegLin)


        self.verticalLayout_3.addWidget(self.groupBoxVal)

        self.groupBoxScale = QGroupBox(self.frameSideBar)
        self.groupBoxScale.setObjectName(u"groupBoxScale")
        self.groupBoxScale.setMinimumSize(QSize(152, 0))
        self.verticalLayout_4 = QVBoxLayout(self.groupBoxScale)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.labelHorizontalScale = QLabel(self.groupBoxScale)
        self.labelHorizontalScale.setObjectName(u"labelHorizontalScale")

        self.verticalLayout_4.addWidget(self.labelHorizontalScale)

        self.comboBoxHorizontalScale = QComboBox(self.groupBoxScale)
        self.comboBoxHorizontalScale.addItem("")
        self.comboBoxHorizontalScale.addItem("")
        self.comboBoxHorizontalScale.setObjectName(u"comboBoxHorizontalScale")
        self.comboBoxHorizontalScale.setMinimumSize(QSize(0, 20))

        self.verticalLayout_4.addWidget(self.comboBoxHorizontalScale)

        self.labelVerticalScale = QLabel(self.groupBoxScale)
        self.labelVerticalScale.setObjectName(u"labelVerticalScale")

        self.verticalLayout_4.addWidget(self.labelVerticalScale)

        self.comboBoxVerticalScale = QComboBox(self.groupBoxScale)
        self.comboBoxVerticalScale.addItem("")
        self.comboBoxVerticalScale.addItem("")
        self.comboBoxVerticalScale.setObjectName(u"comboBoxVerticalScale")

        self.verticalLayout_4.addWidget(self.comboBoxVerticalScale)


        self.verticalLayout_3.addWidget(self.groupBoxScale)

        self.groupBoxKeyVal = QGroupBox(self.frameSideBar)
        self.groupBoxKeyVal.setObjectName(u"groupBoxKeyVal")
        self.groupBoxKeyVal.setMinimumSize(QSize(152, 0))
        self.verticalLayout_5 = QVBoxLayout(self.groupBoxKeyVal)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.Lambda = QLabel(self.groupBoxKeyVal)
        self.Lambda.setObjectName(u"Lambda")

        self.verticalLayout_5.addWidget(self.Lambda)

        self.SD = QLabel(self.groupBoxKeyVal)
        self.SD.setObjectName(u"SD")

        self.verticalLayout_5.addWidget(self.SD)

        self.Theta = QLabel(self.groupBoxKeyVal)
        self.Theta.setObjectName(u"Theta")

        self.verticalLayout_5.addWidget(self.Theta)


        self.verticalLayout_3.addWidget(self.groupBoxKeyVal)

        self.pushButtonUnitToggle = QPushButton(self.frameSideBar)
        self.pushButtonUnitToggle.setObjectName(u"pushButtonUnitToggle")
        self.pushButtonUnitToggle.setMinimumSize(QSize(0, 40))

        self.verticalLayout_3.addWidget(self.pushButtonUnitToggle)


        self.horizontalLayout.addWidget(self.frameSideBar, 0, Qt.AlignRight|Qt.AlignTop)

        MainWindow.setCentralWidget(self.centralwidget)
        self.frameSideBar.raise_()
        self.frameChart.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 979, 26))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuPreprocessing = QMenu(self.menubar)
        self.menuPreprocessing.setObjectName(u"menuPreprocessing")
        self.menuReframe = QMenu(self.menuPreprocessing)
        self.menuReframe.setObjectName(u"menuReframe")
        self.menuHorizontalScale = QMenu(self.menuPreprocessing)
        self.menuHorizontalScale.setObjectName(u"menuHorizontalScale")
        self.menuVerticalScale = QMenu(self.menuPreprocessing)
        self.menuVerticalScale.setObjectName(u"menuVerticalScale")
        self.menuOperations = QMenu(self.menubar)
        self.menuOperations.setObjectName(u"menuOperations")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuPreprocessing.menuAction())
        self.menubar.addAction(self.menuOperations.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionOpen_Multiple)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionDelete_Chart)
        self.menuPreprocessing.addAction(self.menuReframe.menuAction())
        self.menuPreprocessing.addAction(self.menuHorizontalScale.menuAction())
        self.menuPreprocessing.addAction(self.menuVerticalScale.menuAction())
        self.menuPreprocessing.addSeparator()
        self.menuPreprocessing.addAction(self.actionMean)
        self.menuPreprocessing.addAction(self.actionLinear_Regression)
        self.menuReframe.addAction(self.actionReframe_Horizontally)
        self.menuReframe.addAction(self.actionReframe_Vertically)
        self.menuHorizontalScale.addAction(self.actionHorizontalLinear)
        self.menuHorizontalScale.addAction(self.actionHorizontalLogarithmic)
        self.menuVerticalScale.addAction(self.actionVerticalLinear)
        self.menuVerticalScale.addAction(self.actionVerticalLogarithmic)
        self.menuOperations.addAction(self.actionM2)
        self.menuOperations.addAction(self.actionM3)
        self.menuOperations.addAction(self.actionM4_q)
        self.menuOperations.addAction(self.actionFourier)
        self.menuOperations.addSeparator()
        self.menuOperations.addAction(self.actionAll)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpen_Multiple.setText(QCoreApplication.translate("MainWindow", u"Open Multiple", None))
#if QT_CONFIG(shortcut)
        self.actionOpen_Multiple.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save As", None))
#if QT_CONFIG(shortcut)
        self.actionSave_As.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionPrint.setText(QCoreApplication.translate("MainWindow", u"Print", None))
#if QT_CONFIG(shortcut)
        self.actionPrint.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
#endif // QT_CONFIG(shortcut)
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
#if QT_CONFIG(shortcut)
        self.actionExit.setShortcut(QCoreApplication.translate("MainWindow", u"Esc", None))
#endif // QT_CONFIG(shortcut)
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
#if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
#if QT_CONFIG(shortcut)
        self.actionRedo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
#if QT_CONFIG(shortcut)
        self.actionCopy.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
#if QT_CONFIG(shortcut)
        self.actionPaste.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionReframe_Horizontally.setText(QCoreApplication.translate("MainWindow", u"Reframe Horizontally", None))
#if QT_CONFIG(shortcut)
        self.actionReframe_Horizontally.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+H", None))
#endif // QT_CONFIG(shortcut)
        self.actionReframe_Vertically.setText(QCoreApplication.translate("MainWindow", u"Reframe Vertically", None))
#if QT_CONFIG(shortcut)
        self.actionReframe_Vertically.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+J", None))
#endif // QT_CONFIG(shortcut)
        self.actionHorizontalLinear.setText(QCoreApplication.translate("MainWindow", u"Linear", None))
        self.actionHorizontalLogarithmic.setText(QCoreApplication.translate("MainWindow", u"Logarithmic", None))
        self.actionMean.setText(QCoreApplication.translate("MainWindow", u"Mean", None))
#if QT_CONFIG(shortcut)
        self.actionMean.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+M", None))
#endif // QT_CONFIG(shortcut)
        self.actionLinear_Regression.setText(QCoreApplication.translate("MainWindow", u"Linear Regression", None))
#if QT_CONFIG(shortcut)
        self.actionLinear_Regression.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+L", None))
#endif // QT_CONFIG(shortcut)
        self.actionM2.setText(QCoreApplication.translate("MainWindow", u"M2", None))
#if QT_CONFIG(shortcut)
        self.actionM2.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+2", None))
#endif // QT_CONFIG(shortcut)
        self.actionM4_q.setText(QCoreApplication.translate("MainWindow", u"M4/q\u00b2", None))
#if QT_CONFIG(shortcut)
        self.actionM4_q.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+4", None))
#endif // QT_CONFIG(shortcut)
        self.actionFourier.setText(QCoreApplication.translate("MainWindow", u"Fourier", None))
#if QT_CONFIG(shortcut)
        self.actionFourier.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionAll.setText(QCoreApplication.translate("MainWindow", u"All", None))
#if QT_CONFIG(shortcut)
        self.actionAll.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
#if QT_CONFIG(shortcut)
        self.actionCut.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.actionDelete_Chart.setText(QCoreApplication.translate("MainWindow", u"Delete Chart", None))
#if QT_CONFIG(shortcut)
        self.actionDelete_Chart.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+W", None))
#endif // QT_CONFIG(shortcut)
        self.actionVerticalLinear.setText(QCoreApplication.translate("MainWindow", u"Linear", None))
        self.actionVerticalLogarithmic.setText(QCoreApplication.translate("MainWindow", u"Logarithmic", None))
        self.actionM1.setText(QCoreApplication.translate("MainWindow", u"M1", None))
        self.actionM3.setText(QCoreApplication.translate("MainWindow", u"M3", None))
#if QT_CONFIG(shortcut)
        self.actionM3.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+3", None))
#endif // QT_CONFIG(shortcut)
        self.pushButtonPlus.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.groupBoxReframe.setTitle(QCoreApplication.translate("MainWindow", u"Dataset limits", None))
        self.pushButtonHorizontalReframe.setText(QCoreApplication.translate("MainWindow", u"Disable Zoom", None))
        self.pushButtonVerticalReframe.setText(QCoreApplication.translate("MainWindow", u"Noise Control", None))
        self.groupBoxVal.setTitle(QCoreApplication.translate("MainWindow", u"Values on data range :", None))
        self.pushButtonMean.setText(QCoreApplication.translate("MainWindow", u"Mean", None))
        self.pushButtonRegLin.setText(QCoreApplication.translate("MainWindow", u"Linear Regression", None))
        self.groupBoxScale.setTitle(QCoreApplication.translate("MainWindow", u"Scale : ", None))
        self.labelHorizontalScale.setText(QCoreApplication.translate("MainWindow", u"Horizontal :", None))
        self.comboBoxHorizontalScale.setItemText(0, QCoreApplication.translate("MainWindow", u"linear", None))
        self.comboBoxHorizontalScale.setItemText(1, QCoreApplication.translate("MainWindow", u"logarithmic", None))

        self.labelVerticalScale.setText(QCoreApplication.translate("MainWindow", u"Vertical :", None))
        self.comboBoxVerticalScale.setItemText(0, QCoreApplication.translate("MainWindow", u"linear", None))
        self.comboBoxVerticalScale.setItemText(1, QCoreApplication.translate("MainWindow", u"logarithmic", None))

        self.groupBoxKeyVal.setTitle(QCoreApplication.translate("MainWindow", u"Key Values:", None))
        self.Lambda.setText(QCoreApplication.translate("MainWindow", u"Lambda [A] :", None))
        self.SD.setText(QCoreApplication.translate("MainWindow", u"SD [mm] :", None))
        self.Theta.setText(QCoreApplication.translate("MainWindow", u"Theta [\u00b0] :", None))
        self.pushButtonUnitToggle.setText(QCoreApplication.translate("MainWindow", u"Change theta to Q", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuPreprocessing.setTitle(QCoreApplication.translate("MainWindow", u"Preprocessing", None))
        self.menuReframe.setTitle(QCoreApplication.translate("MainWindow", u"Reframe", None))
        self.menuHorizontalScale.setTitle(QCoreApplication.translate("MainWindow", u"Horizontal Scale", None))
        self.menuVerticalScale.setTitle(QCoreApplication.translate("MainWindow", u"Vertical Scale", None))
        self.menuOperations.setTitle(QCoreApplication.translate("MainWindow", u"Operations", None))
    # retranslateUi

